CheminPayslip/Controllers/ExcelDemo3Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CheminPayslip.Models;
using LinqToExcel;

namespace CheminPayslip.Controllers
{
    public class ExcelDemo3Controller : Controller
    {
        private ApplicationDbContext _context;

        public ExcelDemo3Controller()
        {
            _context = new ApplicationDbContext();

        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult ExcelUpload()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadExcel(EmployeeDetails objEmployeeDetails, HttpPostedFileBase fileUpload)
        {
            string data = "";
            var total = _context.Employee2.ToList().Count;
            if (total != 0)
            {
                _context.Database.ExecuteSqlCommand("DELETE FROM EmployeeDetails3");

            }

            if (fileUpload != null)
            {
                if (fileUpload.ContentType == "application/vnd.ms-excel" || fileUpload.ContentType ==
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
                {
                    string filename = fileUpload.FileName;
                    if (filename.EndsWith(".xlsx") || filename.EndsWith(".csv"))
                    {
                        string targetpath = Server.MapPath("~/sheets3/");
                        fileUpload.SaveAs(targetpath + filename);
                        string pathToExcelFile = targetpath + filename;
                        string sheetName = "Sheet1";
                        var excelFile = new ExcelQueryFactory(pathToExcelFile);
                        var empdetails = from a in excelFile.Worksheet<EmployeeDetails3>(sheetName) select a;
                        foreach (var a in empdetails)
                        {

                            if (a.EmployeeId != null)
                            {
                                _context.Employee3.Add(a);


                            }
                            else
                            {
                                data = "Please check your excel sheet,There is a problem";
                                ViewBag.Message = data;
                                return View("ExcelUpload");


                            }

                        }

                        _context.SaveChanges();
                        data = "Successful upload records";
                        ViewBag.Message = data;
                    }
                    else
                    {
                        data = "Please upload spreadsheet of the form csv";
                        ViewBag.Message = data;
                        return View("ExcelUpload");
                    }
                }
                else
                {
                    data = "Please upload a spreadsheet";
                    return View("ExcelUpload");
                }
            }


            return View("ExcelUpload");
        }

    }
}

CheminPayslip/Views/ExcelDemo3/ExcelUpload.cshtml
@{
    ViewBag.Title = "ExcelUpload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    input[type="file"] {
       
        font-size: large;
    }
    button, html input[type="button"], input[type="reset"], input[type="submit"] {
        font-size: large;
    }
</style>
<h2>ExcelUpload</h2>

<div align="center">  
    @if (ViewBag.Message != null)  
    {  
        <span class="alert alert-warning"> @ViewBag.Message</span>  
    }  
    
    <div align="right" class="btn btn-default">  
        @using (Html.BeginForm("UploadExcel", "ExcelDemo3", FormMethod.Post, new { @enctype = "multipart/form-data" }))  
        {  
            <input type="file" id="fileUpload" class="btn btn-primary" name="FileUpload" /><br />  
            <input type="submit" class="btn btn-primary" name="UploadNewEmployee" id="fileUploadExcel" value="Upload Employee Details For @DateTime.Now.AddMonths(-3).ToString("MMMM")" />  
        }  
    </div>  
</div>


@section scripts
{
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>  
  
        $('#fileUploadExcel').click(function (e) {  
            if ($('#fileUpload').val() === "")   
            {  
                sweetAlert("Oops...!!!", "Please select file", "error");  
                return false;  
            }  
  
        });  
  
    </script>  
}